

###
curl -u 'listmonk:lBjRdUAZVu9HxH7f' 'http://localhost:9000/api/subscribers' -H 'Content-Type: application/json' \
    --data '{"email":"dhanushgsec@gmail.com","name":"dhanush"}'

###
curl -u 'listmonk:lBjRdUAZVu9HxH7f' 'http://localhost:9000/api/subscribers?list_id=1&list_id=2&page=1&per_page=100'